version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install Python3
          command: 'apt-get update && sudo apt-get install -y python3'
      - run:
          name: Install WGet
          command: 'apt-get update && sudo apt-get install -y wget'
      - run:
          name: Install Pip3
          command: 'apt-get update && sudo apt-get -y install python3-pip'
      - run:
          name: Install Conan
          command: 'sudo python3 -m pip install conan'
      - run:
          name: Configure Remote Conan Repository Bincrafter
          command: 'conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan'
      - run:
          name: Configure Remote Conan Repository Epitech
          command: 'conan remote add epitech https://api.bintray.com/conan/epitech/public-conan'
      - run:
          name: Install dependecies
          command: 'mkdir build && cd build && conan install .. --build=missing && cd ..'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Install Criterion
          command: 'cd tests && sudo ./install_criterion.sh'
      - run:
          name: Install dependecies
          command: 'cd tests && mkdir build && cd build && conan install ../.. --build=missing && cd ..'
      - run:
          name: Creating Build tests files
          command: 'cd tests && cmake -H. -Bbuild'
      - run:
          name: Creatin Binary Test file
          command: 'cd tests && cmake --build build'
      - run:
          name: Launch Units Tests
          command: 'cd tests && ./build/bin/unit_test'
