name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Install C and C++ header files
      run: |
        sudo apt-get update && sudo apt-get install -y gcc-multilib
      if: matrix.install-headerfiles
    - name: Install conan && conan package tools
      run: |
        python -m pip install --upgrade pip
        pip install conan
        pip install conan_package_tools
    - name: Configure Remote Conan Repository Bincrafter
      run:  conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    - name: Configure Remote Conan Repository Epitech
      run:  conan remote add epitech https://api.bintray.com/conan/epitech/public-conan
    - name: Install dependecies
      run:  mkdir build && cd build && conan install .. --build=missing && cd ..
    - name: Creating Build Files
      run:  cmake -H. -Bbuild
    - name: Creating Binary Files
      run:  cmake --build build
    - name: Install Criterion
      run:  cd tests && sudo ./install_criterion.sh
    - name: Creating Build tests files
      run:  cd tests && cmake -H. -Bbuild
    - name: Creatin Binary Test file
      run:  cd tests && cmake --build build
    - name: Launch Units Tests
      run:  cd tests && ./build/test
